hack to get 'python testall.py' to work on Mac
Before this I'd get a failure like the following when Python 2.7 running
testall.py called out to '/usr/bin/python2.5 test.py ...'. Looks like
Python 2.7 sets MACOSX_DEPLOYMENT_TARGET in its env, which is
inherited for "os.system" calls.

======================================================================
ERROR: markdown2/tm/fenced_code_blocks_syntax_highlighting [extra, fenced-code-blocks, pygments]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_markdown2.py", line 202, in <lambda>
    metadata_path=m)
  File "./test_markdown2.py", line 94, in _assertMarkdownPath
    **extra)
  File "./test_markdown2.py", line 106, in _assertMarkdown
    python_html = markdown2.markdown(text, **opts)
  File "/Users/trentm/tm/python-markdown2/lib/markdown2.py", line 176, in markdown
    use_file_vars=use_file_vars).convert(text)
  File "/Users/trentm/tm/python-markdown2/lib/markdown2.py", line 318, in convert
    text = self._do_fenced_code_blocks(text)
  File "/Users/trentm/tm/python-markdown2/lib/markdown2.py", line 1552, in _do_fenced_code_blocks
    return self._fenced_code_block_re.sub(self._fenced_code_block_sub, text)
  File "/Users/trentm/tm/python-markdown2/lib/markdown2.py", line 1548, in _fenced_code_block_sub
    return self._code_block_sub(match, is_fenced_code_block=True);
  File "/Users/trentm/tm/python-markdown2/lib/markdown2.py", line 1498, in _code_block_sub
    lexer = self._get_pygments_lexer(lexer_name)
  File "/Users/trentm/tm/python-markdown2/lib/markdown2.py", line 1445, in _get_pygments_lexer
    from pygments import lexers, util
  File "/Users/trentm/tm/python-markdown2/deps/pygments/pygments/lexers/__init__.py", line 18, in <module>
    from pygments.plugin import find_plugin_lexers
  File "/Users/trentm/tm/python-markdown2/deps/pygments/pygments/plugin.py", line 39, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/Extras/lib/python/pkg_resources.py", line 651, in <module>
    class Environment(object):
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/Extras/lib/python/pkg_resources.py", line 654, in Environment
    def __init__(self, search_path=None, platform=get_supported_platform(), python=PY_MAJOR):
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/Extras/lib/python/pkg_resources.py", line 55, in get_supported_platform
    plat = get_build_platform(); m = macosVersionString.match(plat)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/Extras/lib/python/pkg_resources.py", line 181, in get_build_platform
    plat = get_platform()
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/util.py", line 78, in get_platform
    cfgvars = get_config_vars()
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/sysconfig.py", line 504, in get_config_vars
    func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/sysconfig.py", line 389, in _init_posix
    raise DistutilsPlatformError(my_msg)
DistutilsPlatformError: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.5" but "10.8" during configure